function t347_setHeight(recid){var el=$('#rec'+recid);var div=el.find(".t347__table");var height=div.width()*0.5625;div.height(height)}
window.t347showvideo=function(recid){$(document).ready(function(){var el=$('#rec'+recid);var videourl='';var youtubeid=$("#rec"+recid+" .t347__video-container").attr('data-content-popup-video-url-youtube');if(youtubeid>''){videourl='https://www.youtube.com/embed/'+youtubeid}
$("#rec"+recid+" .t347__video-container").removeClass("t347__hidden");$("#rec"+recid+" .t347__video-carier").html("<iframe id=\"youtubeiframe"+recid+"\" class=\"t347__iframe\" width=\"100%\" height=\"100%\" src=\""+videourl+"?autoplay=1&rel=0\" frameborder=\"0\" allowfullscreen></iframe>")})}
window.t347hidevideo=function(recid){$(document).ready(function(){$("#rec"+recid+" .t347__video-container").addClass("t347__hidden");$("#rec"+recid+" .t347__video-carier").html("")})}
function t410_init(recid){var el=$('#rec'+recid);var firstimgurl=el.find(".t410__wrapper").attr("data-juxtapose-imgurl-first");var firstimgdescr=el.find(".t410__wrapper").attr("data-juxtapose-imgdescr-first");var firstimgalt=el.find(".t410__wrapper").attr("data-juxtapose-imgalt-first");var secondimgurl=el.find(".t410__wrapper").attr("data-juxtapose-imgurl-second");var secondimgdescr=el.find(".t410__wrapper").attr("data-juxtapose-imgdescr-second");var secondimgalt=el.find(".t410__wrapper").attr("data-juxtapose-imgalt-second");t410_onObjLoad('juxtapose',function(){new juxtapose.JXSlider('#t410-juxtapose__'+recid,[{src:firstimgurl,label:firstimgdescr},{src:secondimgurl,label:secondimgdescr}],{animate:!1,showLabels:!0,showCredits:!1,startingPosition:'50%',makeResponsive:!0,callback:function(){if(firstimgalt.length>0){el.find('.t410__wrapper .jx-image.jx-left img').attr('alt',firstimgalt)}
if(secondimgalt.length>0){el.find('.t410__wrapper .jx-image.jx-right img').attr('alt',secondimgalt)}
if(window.isMobile){el.find('.t410__wrapper').append('<div class="t410__mobile_left"></div><div class="t410__mobile_right"></div>');var hanlerWidth=el.find('.jx-handle').width(),leftSide=el.find('.jx-image.jx-left'),rightSide=el.find('.jx-image.jx-right'),leftWidth=leftSide.width()-hanlerWidth/2,rightWidth=rightSide.width()-hanlerWidth/2,wrapper=el.find('.t410__wrapper'),mobileLeft=el.find('.t410__mobile_left'),mobileRight=el.find('.t410__mobile_right');mobileLeft.css('width',leftWidth);mobileRight.css('width',rightWidth);wrapper.on('touchend',function(){leftWidth=leftSide.width()-hanlerWidth/2;rightWidth=rightSide.width()-hanlerWidth/2;mobileLeft.css('width',leftWidth);mobileRight.css('width',rightWidth)})}}})});el.find('.t410').bind('displayChanged',function(){window.juxtapose.sliders.forEach(function(obj){if(obj.selector==='#t410-juxtapose__'+recid){console.log(obj);obj.setWrapperDimensions();return}})})}
function t410_onObjLoad(objName,okFunc,time){if(typeof window[objName]==='object'){okFunc()}else{var timerId=setTimeout(function checkFuncExist(){if(typeof window[objName]==='object'){okFunc();return}
timerId=setTimeout(checkFuncExist,time||100)})}}
function t670_init(recid){t670_imageHeight(recid);t670_show(recid);t670_hide(recid)}
function t670_show(recid){var el=$('#rec'+recid);var play=el.find('.t670__play');play.click(function(){if($(this).attr('data-slider-video-type')=='youtube'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://www.youtube.com/embed/"+url+"?autoplay=1\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>")}
if($(this).attr('data-slider-video-type')=='vimeo'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://player.vimeo.com/video/"+url+"\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen></iframe>")}
$(this).next().css('z-index','3')})}
function t670_hide(recid){var el=$('#rec'+recid);var body=el.find('.t670__frame');el.on('updateSlider',function(){body.html('').css('z-index','')})}
function t670_imageHeight(recid){var el=$('#rec'+recid);var image=el.find('.t670__separator');image.each(function(){var width=$(this).attr('data-slider-image-width');var height=$(this).attr('data-slider-image-height');var ratio=height/width;var padding=ratio*100;$(this).css('padding-bottom',padding+'%')})}
function t814_init(recid){var el=$('#rec'+recid);t814_setHeight(recid);$(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!=="undefined"&&window.noAdaptive===!0&&window.isMobile){return}
t814_setHeight(recid)}));el.find('.t814').on('displayChanged',function(){t814_setHeight(recid)})}
function t814_setHeight(recid){var el=$('#rec'+recid);var imgWrapperHeight=el.find(".t814__blockimg").height();var blockTextWrapper=el.find(".t814__blocktext-wrapper");var textWrapper=el.find(".t814__blocktext");if($(window).width()>960){textWrapper.css('height',imgWrapperHeight);blockTextWrapper.css('height',textWrapper.outerHeight(!0))}else{blockTextWrapper.css('height','auto')}}